name: release-please-preview

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [master]

permissions:
  contents: read
  pull-requests: write

jobs:
  preview:
    uses: non7top/gh-workflows/.github/workflows/release-please-preview.yml@main
    permissions:
      contents: read
      pull-requests: write
